name: fingerbrow

services:
  linux-builder:
    build:
      context: .
    volumes:
      - ./release:/release
    command: >
      sh -c "pnpm desktop:build:linux &&
      mkdir -p /release &&
      find /release -mindepth 1 -maxdepth 1 -exec rm -rf {} + &&
      mkdir -p /release/appimage /release/deb &&
      cp src-tauri/target/release/bundle/appimage/*.AppImage /release/appimage/ &&
      cp src-tauri/target/release/bundle/deb/*.deb /release/deb/"
